/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/3': RouteRecordInfo<'/posts/3', '/posts/3', Record<never, never>, Record<never, never>>,
    '/posts/9527': RouteRecordInfo<'/posts/9527', '/posts/9527', Record<never, never>, Record<never, never>>,
    '/posts/9528': RouteRecordInfo<'/posts/9528', '/posts/9528', Record<never, never>, Record<never, never>>,
    '/posts/9529': RouteRecordInfo<'/posts/9529', '/posts/9529', Record<never, never>, Record<never, never>>,
    '/posts/9531': RouteRecordInfo<'/posts/9531', '/posts/9531', Record<never, never>, Record<never, never>>,
    '/posts/9533': RouteRecordInfo<'/posts/9533', '/posts/9533', Record<never, never>, Record<never, never>>,
    '/posts/9534': RouteRecordInfo<'/posts/9534', '/posts/9534', Record<never, never>, Record<never, never>>,
    '/posts/从零开始的原神反和谐-马克图布': RouteRecordInfo<'/posts/从零开始的原神反和谐-马克图布', '/posts/从零开始的原神反和谐-马克图布', Record<never, never>, Record<never, never>>,
    '/posts/如何令原神中人物模型随地区改变': RouteRecordInfo<'/posts/如何令原神中人物模型随地区改变', '/posts/如何令原神中人物模型随地区改变', Record<never, never>, Record<never, never>>,
    '/posts/碎碎念': RouteRecordInfo<'/posts/碎碎念', '/posts/碎碎念', Record<never, never>, Record<never, never>>,
    '/posts/d3d': RouteRecordInfo<'/posts/d3d', '/posts/d3d', Record<never, never>, Record<never, never>>,
    '/posts/fhx': RouteRecordInfo<'/posts/fhx', '/posts/fhx', Record<never, never>, Record<never, never>>,
    '/posts/top': RouteRecordInfo<'/posts/top', '/posts/top', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
